### ISSUE TITLE
State preserving with react-hot-loader and markdown-doc-loader

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#239]
With the react-hot-loader enabled #229 , the hmr works fine but the state of "Demo" and child-component of zent will lost after module replacement.

There is a speculation that the markdown series loader cause the bug.

- [ ] Preserve the state 

- [ ] Fix the FOUC

**Comment by cpylua** [comment]
[https://github.com/markdown-doc/react-markdown-doc-loader/blob/master/lib/compile-code.js#L9](https://github.com/markdown-doc/react-markdown-doc-loader/blob/master/lib/compile-code.js#L9)

Each demo block is wrapped within a IIFE in order to isolate contexts. This IIFE returns a react element and gets assigned to a **random** variable.

[https://github.com/markdown-doc/react-markdown-doc-loader/blob/master/lib/index.js#L22](https://github.com/markdown-doc/react-markdown-doc-loader/blob/master/lib/index.js#L22)

Notice the `gensym` call in `prepareAST`.


Using a predicatable variable name or removing the IIFE might help preserving state.

**Comment by LucasIcarus** [comment]
@cpylua Get！

**Comment by cpylua** [comment]
Close.
